# This is the default image for CI on the school's GitLab server.
# Just use this image, unless you have a good reason not to.
#
image: "smblott/dcu-docker-gitlab-ci"

# The make file (Makefile) contains two targets, "build" and run".
#
run:
   script:
      - echo fix me
