# This is the default image for CI on the school's GitLab server.
# Just use this image, unless you have a good reason not to.
#
image: "smblott/dcu-docker-gitlab-ci"

# Your instructions are in the README.txt file in this directory.
#

stages:
   - build
   - test

cache:
   key: global
   paths:
      - add


build:
   stage: build
   script:
      - make build

test-1:
   stage: test
   script:
      - make test
