# This is the default image for CI on the school's GitLab server.
# Just use this image, unless you have a good reason not to.
#
image: "smblott/dcu-docker-gitlab-ci"

variables:
   url: "https://www.python.org/ftp/python/3.9.0/Python-3.9.0.tgz"
   dst: "Python-3.9.0.tgz"

hello:
   script:
      - zsh download.zsh $CACHE $url $dst
