# This is the default image for CI on the school's GitLab server.
# Just use this image, unless you have a good reason not to.
#
image: "smblott/dcu-docker-gitlab-ci"

# The MySQL service requires configuration.  These variables set the database
# and password for the MySQL service.
#
variables:
   MYSQL_DATABASE: "test"
   MYSQL_ROOT_PASSWORD: "SeCrEt"

# Your instructions are in the README file in this directory.
#
hello:
   script:
      - echo hello world
