# This is the default image for CI on the school's GitLab server.
# Just use this image, unless you have a good reason not to.
#
image: "smblott/dcu-docker-gitlab-ci"

# Your instructions are in the README.txt file in this directory.
#
run:
   script:
      - echo fix me
