# This is the default image for CI on the school's GitLab server.
# Just use this image, unless you have a good reason not to.
#
image: "smblott/dcu-docker-gitlab-ci"

# The make file (Makefile) contains two targets, "build" and run".
#
# Separate build and test into two jobs which run as two stages in
# pipeline:
#
#   - https://docs.gitlab.com/ee/ci/yaml/#stage
#

stages:
   - build
   - test



build:
   stage: build
   script:
      - make build

test-1:
   stage: test
   script:
      - make test
