# This is the default image for CI on the school's GitLab server.
# Just use this image, unless you have a good reason not to.
#
image: "smblott/dcu-docker-gitlab-ci"

# The make file (Makefile) contains two targets, "build" and run".
#
# "script" is a sequence of commands to execute for this job.
#
# The format of this file is YAML (https://yaml.org/).
#
# GitLab CI configuration is defined here...
#
#   - https://docs.gitlab.com/ee/ci/yaml/
#
# If you have "gitlab-runner" installed locally, then you can run
# this job like this...
#
#   - gitlab-runner exec shell hello
#   - gitlab-runner docker shell hello
#
# Also, this job will be run automatically whenever you push new
# commits back to GitLab.
#
hello:
   script:
      - echo hello world
